// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");
const { defineConfig, env } = require("prisma/config");

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        url: process.env.PROD_DB_INTERNAL_URL
            ?? (process.env.USE_PROD_DB === "True"
                ? process.env.PROD_DB_URL
                : process.env.DATABASE_URL),
    },
});
